# Run black format. Line length is 79.

name: black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          black --check --verbose --line-length 79 .
